# Generated by Django 4.2.6 on 2023-11-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='carroceria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
