# Generated by Django 4.2.7 on 2023-11-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='reviews',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='reviews',
            field=models.ManyToManyField(to='main.reseña'),
        ),
    ]
