# Generated by Django 4.2.6 on 2023-11-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_perfilusuario_reviews_perfilusuario_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
