# Generated by Django 4.2.6 on 2023-11-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='marco',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
