# Generated by Django 4.2.6 on 2023-11-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vehiculo_marco_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
    ]
