# Generated by Django 4.2.6 on 2023-11-20 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
