# Generated by Django 4.2.6 on 2023-11-21 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_reseña_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(default='marca', on_delete=django.db.models.deletion.CASCADE, to='main.marca'),
        ),
    ]
