# Generated by Django 4.2.6 on 2023-11-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_vehiculo_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='marco',
            new_name='marca',
        ),
    ]
