# Generated by Django 4.2.6 on 2023-11-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_vehiculo_marca'),
        ('main', '0011_alter_vehiculo_imagen'),
    ]

    operations = [
    ]
