# Generated by Django 4.2.6 on 2023-11-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_vehiculo_imagen'),
        ('main', '0012_merge_20231127_1215'),
    ]

    operations = [
    ]
