# Generated by Django 4.2.6 on 2023-11-27 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_20231127_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.marca'),
        ),
    ]
